### ISSUE TITLE
Cannot invoke "dragondance.eng.InstructionInfo.getAddr()" because "inst" is null

### ISSUE THREAD

**Issue by Svieg** [Svieg/dragondance#1]
When calculating a difference between two DynamoRIO traces on a x86 PE binary:

```
Cannot invoke "dragondance.eng.InstructionInfo.getAddr()" because "inst" is null
java.lang.NullPointerException: Cannot invoke "dragondance.eng.InstructionInfo.getAddr()" because "inst" is null
	at dragondance.datasource.CoverageData.difference(CoverageData.java:96)
	at dragondance.datasource.CoverageData.difference(CoverageData.java:209)
	at dragondance.components.MainDockProvider.showMultiCoverageOperation(MainDockProvider.java:463)
	at dragondance.components.MainDockProvider.lambda$buildCoverageListView$5(MainDockProvider.java:590)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-May-10 1508 EDT
Ghidra Version: 10.3
Java Home: /usr/lib/jvm/java-19-openjdk-amd64
JVM Version: Private Build 19.0.2
OS: Linux 6.2.0-27-generic amd64

**Comment by Svieg** [comment]
inst is not null on first execution but seems to be at the end of the loop in `dragondance.datasource.CoverageData.difference(CoverageData.java:96)`

**Comment by Svieg** [comment]
NPE at this instruction: 
```
        0040198a 80 7c 1f        CMP        byte ptr [EDI + EBX*0x1 + 0x1],0x1
                 01 01

**Comment by Svieg** [comment]
In lookupAdddressMapSingle (CoverageData.java:284), :296 gets triggered but addressMap.containsKey(addrKey) is correct:

```
	private InstructionInfo lookupAddressMapSingle(long addrKey) {
		
		List<InstructionInfo> list = null;
		
		if (!this.addressMap.containsKey(addrKey))
			return null;
		
		list = this.addressMap.get(addrKey);
		
		if (list.size()>0)
			return list.get(0);
		
		return null; // line 296
	}
